---
--- Generated by Luanalysis
--- Created by olivi.
--- DateTime: 09/02/2023 18:29
---


local colorPrimaire = {
    {label = "Noir", value = "Black"},
    {label = "Blanc", value = "White"},
    {label = "Gris", value = "Grey"},
    {label = "Rouge", value = "Red"},
    {label = "Bleu", value = "Blue"},
    {label = "Jaune", value = "Yellow"},
    {label = "Vert", value = "Green"},
    {label = "Orange", value = "Orange"},
    {label = "Violet", value = "Purple"},
    {label = "Marron", value = "Brown"},
    {label = "Chrome", value = "Chrome"},
    {label = "Rose", value = "Pink"},
    {label = "Gold", value = "Gold"},
}

function ColorPrimaire()
    local playerPed = PlayerPedId()
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menucolorprim = RageUI.CreateMenu("Couleur Primaire", "Menu Coleur")
        RageUI.Visible(menucolorprim, not RageUI.Visible(menucolorprim))
        while menucolorprim do
            Citizen.Wait(0)
            RageUI.IsVisible(menucolorprim, true, true, true, function()
                for k,v in pairs(colorPrimaire) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            if v.value == "Black" then
                                ColorBlack()
                            elseif v.value == "White" then
                                ColorWhite()
                            elseif v.value == "Grey" then
                                ColorGrey()
                            elseif v.value == "Red" then
                                ColorRed()
                            elseif v.value == "Blue" then
                                ColorBlue()
                            elseif v.value == "Yellow" then
                                ColorYellow()
                            elseif v.value == "Green" then
                                ColorGreen()
                            elseif v.value == "Orange" then
                                ColorOrange()
                            elseif v.value == "Purple" then
                                ColorPurple()
                            elseif v.value == "Brown" then
                                ColorBrown()
                            elseif v.value == "Chrome" then
                                ColorChrome()
                            elseif v.value == "Pink" then
                                ColorPink()
                            elseif v.value == "Gold" then
                                ColorGold()
                            end
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menucolorprim) then
                menucolorprim = RMenu:DeleteType("menucolorprim", true)
            end
        end
    end
end

function ColorSecondaire()
    local playerPed = PlayerPedId()
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menucolorsec = RageUI.CreateMenu("Couleur Secondaire", "Menu Coleur")
        RageUI.Visible(menucolorsec, not RageUI.Visible(menucolorsec))
        while menucolorsec do
            Citizen.Wait(0)
            RageUI.IsVisible(menucolorsec, true, true, true, function()
                for k,v in pairs(colorPrimaire) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            if v.value == "Black" then
                                ColorBlackSecondaire()
                            elseif v.value == "White" then
                                ColorWhiteSecondaire()
                            elseif v.value == "Grey" then
                                ColorGreySecondaire()
                            elseif v.value == "Red" then
                                ColorRedSecondaire()
                            elseif v.value == "Blue" then
                                ColorBlueSecondaire()
                            elseif v.value == "Yellow" then
                                ColorYellowSecondaire()
                            elseif v.value == "Green" then
                                ColorGreenSecondaire()
                            elseif v.value == "Orange" then
                                ColorOrangeSecondaire()
                            elseif v.value == "Purple" then
                                ColorPurpleSecondaire()
                            elseif v.value == "Brown" then
                                ColorBrownSecondaire()
                            elseif v.value == "Chrome" then
                                ColorChromeSecondaire()
                            elseif v.value == "Pink" then
                                ColorPinkSecondaire()
                            elseif v.value == "Gold" then
                                ColorGoldSecondaire()
                            end
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menucolorsec) then
                menucolorsec = RMenu:DeleteType("menucolorsec", true)
            end
        end
    end
end


function ColorVehicle()
    local playerPed = PlayerPedId()
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menucolor = RageUI.CreateMenu("Couleur Véhicule", "Menu Coleur")
        RageUI.Visible(menucolor, not RageUI.Visible(menucolor))
        while menucolor do
            Citizen.Wait(0)
            RageUI.IsVisible(menucolor, true, true, true, function()
                RageUI.ButtonWithStyle("Couleur Primaire", nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                    if Selected then
                        ColorPrimaire()
                    end
                end)
                RageUI.ButtonWithStyle("Couleur Secondaire", nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                    if Selected then
                        ColorSecondaire()
                    end
                end)
                RageUI.ButtonWithStyle("Neons", nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                    if Selected then
                        Neons()
                    end
                end)

                RageUI.ButtonWithStyle("Phares Xénon", nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                    if Selected then
                        Xenon()
                    end
                end)

            end, function()
            end)
            if not RageUI.Visible(menucolor) then
                menucolor = RMenu:DeleteType("Couleur Véhicule", true)
            end
        end
    else
        ESX.ShowNotification("Vous n'êtes pas dans un véhicule")
    end
end

function Neons()
    local playerPed = PlayerPedId()
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuneon = RageUI.CreateMenu("Neons", "Menu Neons")
        RageUI.Visible(menuneon, not RageUI.Visible(menuneon))
        while menuneon do
            Citizen.Wait(0)
            RageUI.IsVisible(menuneon, true, true, true, function()

                RageUI.ButtonWithStyle("Modifier le néon avant droit", nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                    if Selected then
                        neonsAvantDroit()
                    end
                end)

                RageUI.ButtonWithStyle("Modifier le néon avant gauche", nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                    if Selected then
                        neonsAvantGauche()
                    end
                end)

                RageUI.ButtonWithStyle("Modifier le néon arrière droit", nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                    if Selected then
                        neonsArriereDroit()
                    end
                end)

                RageUI.ButtonWithStyle("Modifier le néon arrière gauche", nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                    if Selected then
                        neonsArriereGauche()
                    end
                end)

                RageUI.ButtonWithStyle("Modifier tous les néons", nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                    if Selected then
                        neonsTous()
                    end
                end)

            end, function()
            end)
            if not RageUI.Visible(menuneon) then
                menuneon = RMenu:DeleteType("Neons", true)
            end
        end
    else
        ESX.ShowNotification("Vous n'êtes pas dans un véhicule")
    end
end

function Xenon()
    local playerPed = PlayerPedId()
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuxenon = RageUI.CreateMenu("Phares Xénon", "Menu Phares Xénon")
        RageUI.Visible(menuxenon, not RageUI.Visible(menuxenon))
        while menuxenon do
            Citizen.Wait(0)
            RageUI.IsVisible(menuxenon, true, true, true, function()

                RageUI.ButtonWithStyle("Activer les phares Xénon", nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                    if Selected then
                        SetVehicleXenonLightsColour(vehicle, 1)
                        SetVehicleModKit(vehicle, 0)
                        ToggleVehicleMod(vehicle, 22, true)
                    end
                end)

                RageUI.ButtonWithStyle("Changer la couleur des phares Xénon", nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                    if Selected then
                        XenonColor()
                    end
                end)

            end, function()
            end)
            if not RageUI.Visible(menuxenon) then
                menuxenon = RMenu:DeleteType("Phares Xénon", true)
            end
        end
    else
        ESX.ShowNotification("Vous n'êtes pas dans un véhicule")
    end
end