---
--- Generated by Luanalysis
--- Created by olivi.
--- DateTime: 14/02/2023 00:46
---

function UpgradeVehicleEngine()
    local playerPed = PlayerPedId()
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuEngineLevel = RageUI.CreateMenu("Moteur Level", "Menu Moteur Level")
        RageUI.Visible(menuEngineLevel, not RageUI.Visible(menuEngineLevel))
        while menuEngineLevel do
            Citizen.Wait(0)
            RageUI.IsVisible(menuEngineLevel, true, true, true, function()
                for k,v in pairs(Engine) do
                    RageUI.Checkbox(v.label, nil, Upgrade, {}, function(Hovered, Active, Selected, Checked)
                        Upgrade = Checked
                        if v.value == 11 then
                            ToggleVehicleMod(GetVehiclePedIsIn(playerPed, false), 11, true)
                        elseif v.value == 12 then
                            ToggleVehicleMod(GetVehiclePedIsIn(playerPed, false), 11, true)
                        elseif v.value == 13 then
                            ToggleVehicleMod(GetVehiclePedIsIn(playerPed, false), 11, true)
                        elseif v.value == 14 then
                            ToggleVehicleMod(GetVehiclePedIsIn(playerPed, false), 11, true)
                        else
                            Checked = false
                        end

                    end)
                end
            end)
            if not RageUI.Visible(menuEngineLevel) then
                menuEngineLevel = RMenu:DeleteType("menuEngineLevel", true)
            end
        end
    end
end