---
--- Generated by Luanalysis
--- Created by olivi.
--- DateTime: 14/02/2023 00:03
---

ColorColorBlack = {
    { index = 0, label = "noir"},
    { index = 1, label = "graphite"},
    { index = 2, label = "noir Méttallisé"},
    { index = 3, label = "acier Fondu"},
    { index = 11, label = "noir Anthracite"},
    { index = 12, label = "noir Mat"},
    { index = 15, label = "nuit Sombre"},
    { index = 16, label = "noir Profond"},
    { index = 21, label = "pétrol"},
    { index = 147, label = "carbon"}
}

ColorColorWhite = {
    { index = 106, label = "vanille"},
    { index = 107, label = "crème"},
    { index = 111, label = "blanc"},
    { index = 112, label = "blanc Polair"},
    { index = 113, label = "beige"},
    { index = 121, label = "blanc Mat"},
    { index = 122, label = "neige"},
    { index = 131, label = "coton"},
    { index = 132, label = "albâtre"},
    { index = 134, label = "blanc Pure"}
}

ColorColorGrey = {
    { index = 4, label = "Argenté"},
    { index = 5, label = "Gris Métallisé"},
    { index = 6, label = "Acier Laminé"},
    { index = 7, label = "Gris Foncé"},
    { index = 8, label = "Gris Rocheux"},
    { index = 9, label = "Gris Nuit"},
    { index = 10, label = "Aluminium"},
    { index = 13, label = "Gris Mat"},
    { index = 14, label = "Gris Clair"},
    { index = 17, label = "Gris Bitume"},
    { index = 18, label = "Gris Béton"},
    { index = 19, label = "Argent Sombre"},
    { index = 20, label = "Magnésite"},
    { index = 22, label = "nickel"},
    { index = 23, label = "zinc"},
    { index = 24, label = "dolomite"},
    { index = 25, label = "Argent Bleuté"},
    { index = 26, label = "Titane"},
    { index = 66, label = "Acier Bleue"},
    { index = 93, label = "Champagne"},
    { index = 144, label = "Gris Chasseur"},
    { index = 156, label = "gris"}
}

ColorColorRed = {
    { index = 27, label = "rouge"},
    { index = 28, label = "Rouge Turin"},
    { index = 29, label = "Coquelicot"},
    { index = 30, label = "Rouge Cuivré"},
    { index = 31, label = "Rouge Cardinal"},
    { index = 32, label = "Rouge Brique"},
    { index = 33, label = "Grenat"},
    { index = 34, label = "Pourpre"},
    { index = 35, label = "Framboise"},
    { index = 39, label = "Rouge Mat"},
    { index = 40, label = "Rouge Foncé"},
    { index = 43, label = "Rouge Pulpeux"},
    { index = 44, label = "Rouge Brillant"},
    { index = 46, label = "Rouge Pale"},
    { index = 143, label = "Rouge Vin"},
    { index = 150, label = "Volcano"}
}

ColorColorPink = {
    { index = 135, label = "rose Electrique"},
    { index = 136, label = "rose Saumon"},
    { index = 137, label = "rose Dragée"}
}

ColorColorBlue = {
    { index = 54, label = "topaze"},
    { index = 60, label = "bleu clair"},
    { index = 61, label = "bleu galaxy"},
    { index = 62, label = "bleu foncé"},
    { index = 63, label = "bleu azur"},
    { index = 64, label = "bleu marine"},
    { index = 65, label = "lapis lazuli"},
    { index = 67, label = "bleu diamant"},
    { index = 68, label = "surfer"},
    { index = 69, label = "pastel"},
    { index = 70, label = "bleu celeste"},
    { index = 73, label = "bleu rally"},
    { index = 74, label = "bleu paradis"},
    { index = 75, label = "bleu nuit"},
    { index = 77, label = "bleu cyan"},
    { index = 78, label = "cobalt"},
    { index = 79, label = "bleu electrique"},
    { index = 80, label = "bleu horizon"},
    { index = 82, label = "bleu métallisé"},
    { index = 83, label = "aigue marine"},
    { index = 84, label = "bleu agathe"},
    { index = 85, label = "zirconium"},
    { index = 86, label = "spinelle"},
    { index = 87, label = "tourmaline"},
    { index = 127, label = "paradis"},
    { index = 140, label = "bubble gum"},
    { index = 141, label = "bleu minuit"},
    { index = 146, label = "bleu interdit"},
    { index = 157, label = "bleu glacier"}
}

ColorColorYellow = {
    { index = 42, label = "jaune"},
    { index = 88, label = "Jaune Blé"},
    { index = 89, label = "Jaune Rally"},
    { index = 91, label = "Jaune Clair"},
    { index = 126, label = "Jaune Pâle"}
}

ColorColorGreen = {
    { index = 49, label = "Vert Foncé"},
    { index = 50, label = "Vert Rally"},
    { index = 51, label = "Vert Sapin"},
    { index = 52, label = "Vert Olive"},
    { index = 53, label = "Vert Clair"},
    { index = 55, label = "Vert Lime"},
    { index = 56, label = "Vert Forêt"},
    { index = 57, label = "Vert Pelouse"},
    { index = 58, label = "Vert Impérial"},
    { index = 59, label = "Vert Bouteille"},
    { index = 92, label = "Vert Citrus"},
    { index = 125, label = "Vert Anis"},
    { index = 128, label = "Kaki"},
    { index = 133, label = "Vert Army"},
    { index = 151, label = "Vert Sombre"},
    { index = 152, label = "Vert Chasseur"},
    { index = 155, label = "Amarylisse"}
}

ColorColorOrange = {
    { index = 36, label = "Tangerine"},
    { index = 38, label = "orange"},
    { index = 41, label = "Orange Mat"},
    { index = 123, label = "Orange Clair"},
    { index = 124, label = "Pèche"},
    { index = 130, label = "Citrouille"},
    { index = 138, label = "Orange Lambo"}
}

ColorColorBrown = {
    { index = 45, label = "Cuivre"},
    { index = 47, label = "Marronclair"},
    { index = 48, label = "Marron Foncé"},
    { index = 90, label = "Bronze"},
    { index = 94, label = "Marron Métallisé"},
    { index = 95, label = "Expresso"},
    { index = 96, label = "Chocolat"},
    { index = 97, label = "Terre Cuite"},
    { index = 98, label = "Marbre"},
    { index = 99, label = "Sable"},
    { index = 100, label = "Sépia"},
    { index = 101, label = "Bison"},
    { index = 102, label = "Palmier"},
    { index = 103, label = "Caramel"},
    { index = 104, label = "Rouille"},
    { index = 105, label = "Chataigne"},
    { index = 108, label = "marron"},
    { index = 109, label = "Noisette"},
    { index = 110, label = "Coquillage"},
    { index = 114, label = "Acajou"},
    { index = 115, label = "Chaudron"},
    { index = 116, label = "Blond"},
    { index = 129, label = "Gravillon"},
    { index = 153, label = "Terre Foncé"},
    { index = 154, label = "Désert"}
}

ColorColorPurple = {
    { index = 71, label = "Indigo"},
    { index = 72, label = "Violet Profond"},
    { index = 76, label = "Violet Foncé"},
    { index = 81, label = "Améthyste"},
    { index = 142, label = "Violet Mystique"},
    { index = 145, label = "Violet Métallisé"},
    { index = 148, label = "Violet Mat"},
    { index = 149, label = "Violet Profond Mat"}
}

ColorColorChrome = {
    { index = 117, label = "chrome Brossé"},
    { index = 118, label = "chrome Noir"},
    { index = 119, label = "aluminum Brossé"},
    { index = 120, label = "chrome"}
}

ColorColorGold = {
    { index = 37, label = "or"},
    { index = 158, label = "Or Pure"},
    { index = 159, label = "Or Brossé"},
    { index = 160, label = "Or Clair"}
}

function ColorBlack()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menub = RageUI.CreateMenu("Couleur Noir", "Couleur")
        RageUI.Visible(menub, not RageUI.Visible(menub))
        while menub do
            Citizen.Wait(0)
            RageUI.IsVisible(menub, true, true, true, function()
                for k,v in pairs(ColorColorBlack) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menub) then
                menub = RMenu:DeleteType("menub", true)
            end
        end
    end
end

function ColorWhite()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuW = RageUI.CreateMenu("Couleur Blanc", "Couleur")
        RageUI.Visible(menuW, not RageUI.Visible(menuW))
        while menuW do
            Citizen.Wait(0)
            RageUI.IsVisible(menuW, true, true, true, function()
                for k,v in pairs(ColorColorWhite) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuW) then
                menuW = RMenu:DeleteType("menuW", true)
            end
        end
    end
end

function ColorGrey()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuG = RageUI.CreateMenu("Couleur Gris", "Couleur")
        RageUI.Visible(menuG, not RageUI.Visible(menuG))
        while menuG do
            Citizen.Wait(0)
            RageUI.IsVisible(menuG, true, true, true, function()
                for k,v in pairs(ColorColorGrey) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuG) then
                menuG = RMenu:DeleteType("menuG", true)
            end
        end
    end
end

function ColorRed()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuR = RageUI.CreateMenu("Couleur Rouge", "Couleur")
        RageUI.Visible(menuR, not RageUI.Visible(menuR))
        while menuR do
            Citizen.Wait(0)
            RageUI.IsVisible(menuR, true, true, true, function()
                for k,v in pairs(ColorColorRed) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuR) then
                menuR = RMenu:DeleteType("menuR", true)
            end
        end
    end
end

function ColorYellow()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuY = RageUI.CreateMenu("Couleur Jaune", "Couleur")
        RageUI.Visible(menuY, not RageUI.Visible(menuY))
        while menuY do
            Citizen.Wait(0)
            RageUI.IsVisible(menuY, true, true, true, function()
                for k,v in pairs(ColorColorYellow) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuY) then
                menuY = RMenu:DeleteType("menuY", true)
            end
        end
    end
end

function ColorGreen()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuG = RageUI.CreateMenu("Couleur Vert", "Couleur")
        RageUI.Visible(menuG, not RageUI.Visible(menuG))
        while menuG do
            Citizen.Wait(0)
            RageUI.IsVisible(menuG, true, true, true, function()
                for k,v in pairs(ColorColorGreen) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuG) then
                menuG = RMenu:DeleteType("menuG", true)
            end
        end
    end
end

function ColorOrange()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuO = RageUI.CreateMenu("Couleur Orange", "Couleur")
        RageUI.Visible(menuO, not RageUI.Visible(menuO))
        while menuO do
            Citizen.Wait(0)
            RageUI.IsVisible(menuO, true, true, true, function()
                for k,v in pairs(ColorColorOrange) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuO) then
                menuO = RMenu:DeleteType("menuO", true)
            end
        end
    end
end

function ColorPurple()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuP = RageUI.CreateMenu("Couleur Violet", "Couleur")
        RageUI.Visible(menuP, not RageUI.Visible(menuP))
        while menuP do
            Citizen.Wait(0)
            RageUI.IsVisible(menuP, true, true, true, function()
                for k,v in pairs(ColorColorPurple) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuP) then
                menuP = RMenu:DeleteType("menuP", true)
            end
        end
    end
end

function ColorPink()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuRose = RageUI.CreateMenu("Couleur Rose", "Couleur")
        RageUI.Visible(menuRose, not RageUI.Visible(menuRose))
        while menuRose do
            Citizen.Wait(0)
            RageUI.IsVisible(menuRose, true, true, true, function()
                for k,v in pairs(ColorColorPink) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuRose) then
                menuRose = RMenu:DeleteType("menuRose", true)
            end
        end
    end
end

function ColorChrome()
    local veh = GetVehiclePedIsIn(playerPed, false)
    local playerPed = PlayerPedId()
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuChrome = RageUI.CreateMenu("Couleur Chrome", "Couleur")
        RageUI.Visible(menuChrome, not RageUI.Visible(menuChrome))
        while menuChrome do
            Citizen.Wait(0)
            RageUI.IsVisible(menuChrome, true, true, true, function()
                for k,v in pairs(ColorColorChrome) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuChrome) then
                menuChrome = RMenu:DeleteType("menuChrome", true)
            end
        end
    end
end

function ColorGold()
    local veh = GetVehiclePedIsIn(playerPed, false)
    local playerPed = PlayerPedId()
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuGold = RageUI.CreateMenu("Couleur Or", "Couleur")
        RageUI.Visible(menuGold, not RageUI.Visible(menuGold))
        while menuGold do
            Citizen.Wait(0)
            RageUI.IsVisible(menuGold, true, true, true, function()
                for k,v in pairs(ColorColorGold) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuGold) then
                menuGold = RMenu:DeleteType("menuGold", true)
            end
        end
    end
end

function ColorBlue()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuBleu = RageUI.CreateMenu("Couleur Bleu", "Couleur")
        RageUI.Visible(menuBleu, not RageUI.Visible(menuBleu))
        while menuBleu do
            Citizen.Wait(0)
            RageUI.IsVisible(menuBleu, true, true, true, function()
                for k,v in pairs(ColorColorBlue) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuBleu) then
                menuBleu = RMenu:DeleteType("menuBleu", true)
            end
        end
    end
end

function ColorBrown()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuBrown = RageUI.CreateMenu("Couleur Marron", "Couleur")
        RageUI.Visible(menuBrown, not RageUI.Visible(menuBrown))
        while menuBrown do
            Citizen.Wait(0)
            RageUI.IsVisible(menuBrown, true, true, true, function()
                for k,v in pairs(ColorColorBrown) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, v.index, GetVehicleColours(veh))
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuBrown) then
                menuBrown = RMenu:DeleteType("menuBrown", true)
            end
        end
    end
end

-- Faire la couleur secondaire

function ColorBlackSecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuBlackSecondaire = RageUI.CreateMenu("Couleur Noir", "Couleur")
        RageUI.Visible(menuBlackSecondaire, not RageUI.Visible(menuBlackSecondaire))
        while menuBlackSecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuBlackSecondaire, true, true, true, function()
                for k,v in pairs(ColorColorBlack) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuBlackSecondaire) then
                menuBlackSecondaire = RMenu:DeleteType("menuBlackSecondaire", true)
            end
        end
    end
end

function ColorWhiteSecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuWhiteSecondaire = RageUI.CreateMenu("Couleur Blanc", "Couleur")
        RageUI.Visible(menuWhiteSecondaire, not RageUI.Visible(menuWhiteSecondaire))
        while menuWhiteSecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuWhiteSecondaire, true, true, true, function()
                for k,v in pairs(ColorColorWhite) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuWhiteSecondaire) then
                menuWhiteSecondaire = RMenu:DeleteType("menuWhiteSecondaire", true)
            end
        end
    end
end

function ColorRedSecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuRedSecondaire = RageUI.CreateMenu("Couleur Rouge", "Couleur")
        RageUI.Visible(menuRedSecondaire, not RageUI.Visible(menuRedSecondaire))
        while menuRedSecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuRedSecondaire, true, true, true, function()
                for k,v in pairs(ColorColorRed) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuRedSecondaire) then
                menuRedSecondaire = RMenu:DeleteType("menuRedSecondaire", true)
            end
        end
    end
end

function ColorYellowSecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuYellowSecondaire = RageUI.CreateMenu("Couleur Jaune", "Couleur")
        RageUI.Visible(menuYellowSecondaire, not RageUI.Visible(menuYellowSecondaire))
        while menuYellowSecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuYellowSecondaire, true, true, true, function()
                for k,v in pairs(ColorColorYellow) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuYellowSecondaire) then
                menuYellowSecondaire = RMenu:DeleteType("menuYellowSecondaire", true)
            end
        end
    end
end

function ColorGreenSecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuGreenSecondaire = RageUI.CreateMenu("Couleur Vert", "Couleur")
        RageUI.Visible(menuGreenSecondaire, not RageUI.Visible(menuGreenSecondaire))
        while menuGreenSecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuGreenSecondaire, true, true, true, function()
                for k,v in pairs(ColorColorGreen) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuGreenSecondaire) then
                menuGreenSecondaire = RMenu:DeleteType("menuGreenSecondaire", true)
            end
        end
    end
end

function ColorBlueSecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuBlueSecondaire = RageUI.CreateMenu("Couleur Bleu", "Couleur")
        RageUI.Visible(menuBlueSecondaire, not RageUI.Visible(menuBlueSecondaire))
        while menuBlueSecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuBlueSecondaire, true, true, true, function()
                for k,v in pairs(ColorColorBlue) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuBlueSecondaire) then
                menuBlueSecondaire = RMenu:DeleteType("menuBlueSecondaire", true)
            end
        end
    end
end

function ColorOrangeSecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuOrangeSecondaire = RageUI.CreateMenu("Couleur Orange", "Couleur")
        RageUI.Visible(menuOrangeSecondaire, not RageUI.Visible(menuOrangeSecondaire))
        while menuOrangeSecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuOrangeSecondaire, true, true, true, function()
                for k,v in pairs(ColorColorOrange) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuOrangeSecondaire) then
                menuOrangeSecondaire = RMenu:DeleteType("menuOrangeSecondaire", true)
            end
        end
    end
end

function ColorPurpleSecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuPurpleSecondaire = RageUI.CreateMenu("Couleur Violet", "Couleur")
        RageUI.Visible(menuPurpleSecondaire, not RageUI.Visible(menuPurpleSecondaire))
        while menuPurpleSecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuPurpleSecondaire, true, true, true, function()
                for k,v in pairs(ColorColorPurple) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuPurpleSecondaire) then
                menuPurpleSecondaire = RMenu:DeleteType("menuPurpleSecondaire", true)
            end
        end
    end
end


function ColorGreySecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuGreySecondaire = RageUI.CreateMenu("Couleur Gris", "Couleur")
        RageUI.Visible(menuGreySecondaire, not RageUI.Visible(menuGreySecondaire))
        while menuGreySecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuGreySecondaire, true, true, true, function()
                for k,v in pairs(ColorColorGrey) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuGreySecondaire) then
                menuGreySecondaire = RMenu:DeleteType("menuGreySecondaire", true)
            end
        end
    end
end

function ColorBrownSecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuBrownSecondaire = RageUI.CreateMenu("Couleur Marron", "Couleur")
        RageUI.Visible(menuBrownSecondaire, not RageUI.Visible(menuBrownSecondaire))
        while menuBrownSecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuBrownSecondaire, true, true, true, function()
                for k,v in pairs(ColorColorBrown) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuBrownSecondaire) then
                menuBrownSecondaire = RMenu:DeleteType("menuBrownSecondaire", true)
            end
        end
    end
end

function ColorChromeSecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuChromeSecondaire = RageUI.CreateMenu("Couleur Chrome", "Couleur")
        RageUI.Visible(menuChromeSecondaire, not RageUI.Visible(menuChromeSecondaire))
        while menuChromeSecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuChromeSecondaire, true, true, true, function()
                for k,v in pairs(ColorColorChrome) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuChromeSecondaire) then
                menuChromeSecondaire = RMenu:DeleteType("menuChromeSecondaire", true)
            end
        end
    end
end

function ColorGoldSecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuGoldSecondaire = RageUI.CreateMenu("Couleur Or", "Couleur")
        RageUI.Visible(menuGoldSecondaire, not RageUI.Visible(menuGoldSecondaire))
        while menuGoldSecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuGoldSecondaire, true, true, true, function()
                for k,v in pairs(ColorColorGold) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuGoldSecondaire) then
                menuGoldSecondaire = RMenu:DeleteType("menuGoldSecondaire", true)
            end
        end
    end
end

function ColorPinkSecondaire()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuPinkSecondaire = RageUI.CreateMenu("Couleur Rose", "Couleur")
        RageUI.Visible(menuPinkSecondaire, not RageUI.Visible(menuPinkSecondaire))
        while menuPinkSecondaire do
            Citizen.Wait(0)
            RageUI.IsVisible(menuPinkSecondaire, true, true, true, function()
                for k,v in pairs(ColorColorPink) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleColours(veh, GetVehicleColours(veh), v.index)
                        end
                    end)
                end
            end, function()
            end)
            if not RageUI.Visible(menuPinkSecondaire) then
                menuPinkSecondaire = RMenu:DeleteType("menuPinkSecondaire", true)
            end
        end
    end
end