---
--- Generated by Luanalysis
--- Created by olivi.
--- DateTime: 14/02/2023 00:20
---

local colorNeonsP = {
    { label = "Blanc",	r = 255, g = 255, b = 255, value=1},
    { label = "Slate Gray",	r = 112, g = 128, b = 144, value=2},
    { label = "Blue", r = 0, g = 0, b = 255, value=3},
    { label = "Light Blue",	r = 0, 	g = 150, b = 255, value=4},
    { label = "Navy Blue", 	r = 0, 	g = 0, 	b = 128, value=5},
    { label = "Sky Blue", 	r = 135, g = 206, b = 235, value=6},
    { label = "Turquoise", 	r = 0, 	g = 245, b = 255},
    { label = "Mint Green", r = 50, g = 255, b = 155, value=7},
    { label = "Lime Green", r = 0, 	g = 255, b = 0, value=8},
    { label = "Olive", 		r = 128, g = 128, b = 0, value=9},
    { label = "Jaune", 	r = 255, g = 255, b = 0, value=10},
    { label = "Or", r = 255, g = 215, 	b = 0, value=11},
    { label = "Orange",	r = 255, g = 165, b = 0, value=12},
    { label = "Blé", r = 245, g = 222, 	b = 179, value=13},
    { label = "Rouge",	r = 255, g = 0, b = 0, value=14},
    { label = "Rose", 	r = 255, g = 161, b = 211, value=15},
    { label = "Rose clair",	r = 255, g = 0, b = 255, value=16},
    { label = "Violet", r = 153, g = 0, b = 153, value=17},
    { label = "Ivory", 	r = 41, g = 36, b = 33, value=18}
}

function neonsAvantDroit()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuNeonsAvantDroit = RageUI.CreateMenu("Neons Avant Droit", "Menu Neons")
        RageUI.Visible(menuNeonsAvantDroit, not RageUI.Visible(menuNeonsAvantDroit))
        while menuNeonsAvantDroit do
            Citizen.Wait(0)
            RageUI.IsVisible(menuNeonsAvantDroit, true, true, true, function()
                for k,v in pairs(colorNeonsP) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleNeonLightEnabled(veh, 0, true)
                            SetVehicleNeonLightEnabled(veh, 1, false)
                            SetVehicleNeonLightEnabled(veh, 2, false)
                            SetVehicleNeonLightEnabled(veh, 3, false)
                            SetVehicleNeonLightsColour(veh, v.r, v.g, v.b)
                        end
                    end)
                end
            end)
            if not RageUI.Visible(menuNeonsAvantDroit) then
                menuNeonsAvantDroit = RMenu:DeleteType("menuNeonsAvantDroit", true)
            end
        end
    end
end

function neonsAvantGauche()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuNeonsAvantGauche = RageUI.CreateMenu("Neons Avant Gauche", "Menu Neons")
        RageUI.Visible(menuNeonsAvantGauche, not RageUI.Visible(menuNeonsAvantGauche))
        while menuNeonsAvantGauche do
            Citizen.Wait(0)
            RageUI.IsVisible(menuNeonsAvantGauche, true, true, true, function()
                for k,v in pairs(colorNeonsP) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleNeonLightEnabled(veh, 0, false)
                            SetVehicleNeonLightEnabled(veh, 1, true)
                            SetVehicleNeonLightEnabled(veh, 2, false)
                            SetVehicleNeonLightEnabled(veh, 3, false)
                            SetVehicleNeonLightsColour(veh, v.r, v.g, v.b)
                        end
                    end)
                end
            end)
            if not RageUI.Visible(menuNeonsAvantGauche) then
                menuNeonsAvantGauche = RMenu:DeleteType("menuNeonsAvantGauche", true)
            end
        end
    end
end

function neonsArriereDroit()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuNeonsArriereDroit = RageUI.CreateMenu("Neons Arrière Droit", "Menu Neons")
        RageUI.Visible(menuNeonsArriereDroit, not RageUI.Visible(menuNeonsArriereDroit))
        while menuNeonsArriereDroit do
            Citizen.Wait(0)
            RageUI.IsVisible(menuNeonsArriereDroit, true, true, true, function()
                for k,v in pairs(colorNeonsP) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleNeonLightEnabled(veh, 0, false)
                            SetVehicleNeonLightEnabled(veh, 1, false)
                            SetVehicleNeonLightEnabled(veh, 2, true)
                            SetVehicleNeonLightEnabled(veh, 3, false)
                            SetVehicleNeonLightsColour(veh, v.r, v.g, v.b)
                        end
                    end)
                end
            end)
            if not RageUI.Visible(menuNeonsArriereDroit) then
                menuNeonsArriereDroit = RMenu:DeleteType("menuNeonsArriereDroit", true)
            end
        end
    end
end

function neonsArriereGauche()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuNeonsArriereGauche = RageUI.CreateMenu("Neons Arrière Gauche", "Menu Neons")
        RageUI.Visible(menuNeonsArriereGauche, not RageUI.Visible(menuNeonsArriereGauche))
        while menuNeonsArriereGauche do
            Citizen.Wait(0)
            RageUI.IsVisible(menuNeonsArriereGauche, true, true, true, function()
                for k,v in pairs(colorNeonsP) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleNeonLightEnabled(veh, 0, false)
                            SetVehicleNeonLightEnabled(veh, 1, false)
                            SetVehicleNeonLightEnabled(veh, 2, false)
                            SetVehicleNeonLightEnabled(veh, 3, true)
                            SetVehicleNeonLightsColour(veh, v.r, v.g, v.b)
                        end
                    end)
                end
            end)
            if not RageUI.Visible(menuNeonsArriereGauche) then
                menuNeonsArriereGauche = RMenu:DeleteType("menuNeonsArriereGauche", true)
            end
        end
    end
end

function neonsTous()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuNeonsTous = RageUI.CreateMenu("Neons Tous", "Menu Neons")
        RageUI.Visible(menuNeonsTous, not RageUI.Visible(menuNeonsTous))
        while menuNeonsTous do
            Citizen.Wait(0)
            RageUI.IsVisible(menuNeonsTous, true, true, true, function()
                for k,v in pairs(colorNeonsP) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Selected then
                            SetVehicleNeonLightEnabled(veh, 0, true)
                            SetVehicleNeonLightEnabled(veh, 1, true)
                            SetVehicleNeonLightEnabled(veh, 2, true)
                            SetVehicleNeonLightEnabled(veh, 3, true)
                            SetVehicleNeonLightsColour(veh, v.r, v.g, v.b)
                        end
                    end)
                end
            end)
            if not RageUI.Visible(menuNeonsTous) then
                menuNeonsTous = RMenu:DeleteType("menuNeonsTous", true)
            end
        end
    end
end