---
--- Generated by Luanalysis
--- Created by olivi.
--- DateTime: 20/02/2023 17:51
---

local ESX = nil

Citizen.CreateThread(function() while ESX == nil do TriggerEvent("esx:stgetSharedObject", function(obj) ESX = obj end) Wait(1) end end)

local zone = {
    {label = "Zone 1 - 5m", radius = 5.0},
    {label = "Zone 2 - 50m", radius = 50.0},
    {label = "Zone 3 - 100m", radius = 100.0},
    {label = "Zone 4 - 150m", radius = 150.0},
}

local InVeh = false

function DeleteVehicle()
    local playerPed = PlayerPedId()
    local playerCoords = GetEntityCoords(playerPed, false)
    if InVeh == false then
        RageUI.CloseAll()
        local menuDelete = RageUI.CreateMenu("Suppression", "Menu Suppression")
        RageUI.Visible(menuDelete, not RageUI.Visible(menuDelete))
        while menuDelete do
            Citizen.Wait(0)
            RageUI.IsVisible(menuDelete, true, true, true, function()
                RageUI.ButtonWithStyle("Supprimer", nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                    if Active then
                        local playerCoords = GetEntityCoords(playerPed, false)
                        local vehicle = ESX.Game.GetClosestVehicle(playerCoords)
                        local vehicleCoords = GetEntityCoords(vehicle, false)
                        local distance = GetDistanceBetweenCoords(playerCoords, vehicleCoords, true)

                        DrawMarker(1, vehicleCoords.x, vehicleCoords.y, vehicleCoords.z - 1.0, 0, 0, 0, 0, 0, 0, 5.0, 5.0, 50.0, 0, 255, 0, 100, 0, 0, 0, 0)
                    end
                    if Selected then
                        DeleteEntity(vehicle)
                    end
                end)
                
                for k,v in ipairs(zone) do
                    RageUI.ButtonWithStyle(v.label, nil, {RightLabel = "→"}, true, function(Hovered, Active, Selected)
                        if Active then
                            local playerCoords = GetEntityCoords(playerPed, false)
                            DrawMarker(1, playerCoords.x, playerCoords.y, playerCoords.z - 1.0, 0, 0, 0, 0, 0, 0, v.radius, v.radius, 50.0, 0, 255, 0, 100, 0, 0, 0, 0)
                        end
                        if Selected then
                            local vehciles = ESX.Game.GetVehiclesInArea(playerCoords, v.radius)
                            for i = 1, #vehciles, 1 do
                                if DoesEntityExist(vehciles[i]) then
                                    DeleteEntity(vehciles[i])
                                end
                            end
                        end
                    end)
                end
            end)
            if not RageUI.Visible(menuDelete) then
                menuDelete = RMenu:DeleteType("menuDelete", true)
            end
        end
    end
end