---
--- Generated by Luanalysis
--- Created by olivi.
--- DateTime: 09/02/2023 16:02
---

self = {
    fenetreIndex = 1,
    fenetreList = { "Ouvrir", "Fermer" },
    capotIndex = 1,
    capotList = { "Ouvrir", "Fermer" },
    portesIndex = 1,
    portesList = { "Avant Droit", "Avant Gauche", "Arrière Droit", "Arrière Gauche"},
    portesIndex2 = 1,
    portesList2 = { "Avant Droit", "Avant Gauche", "Arrière Droit", "Arrière Gauche"},
    coffreIndex = 1,
    coffreList = { "Ouvrir", "Fermer" },
}


function KeyboardInput(TextEntry, ExampleText, MaxStringLenght)

    AddTextEntry('FMMC_KEY_TIP1', TextEntry)
    DisplayOnscreenKeyboard(1, "FMMC_KEY_TIP1", "", ExampleText, "", "", "", MaxStringLenght)
    blockinput = true

    while UpdateOnscreenKeyboard() ~= 1 and UpdateOnscreenKeyboard() ~= 2 do
        Citizen.Wait(0)
    end

    if UpdateOnscreenKeyboard() ~= 2 then
        local result = GetOnscreenKeyboardResult()
        Citizen.Wait(500)
        blockinput = false
        return result
    else
        Citizen.Wait(500)
        blockinput = false
        return nil
    end
end