---
--- Generated by Luanalysis
--- Created by olivi.
--- DateTime: 09/02/2023 18:28
---

function OptionsVehicle()
    local playerPed = PlayerPedId()
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuoptions = RageUI.CreateMenu("Options Véhicule", "Options Véhicule")
        RageUI.Visible(menuoptions, not RageUI.Visible(menuoptions))

        while menuoptions do
            Citizen.Wait(0)
            RageUI.IsVisible(menuoptions, true, true, true, function()
                RageUI.Checkbox("Arrêter / Démarrer le moteur", nil, engine, {}, function(Hovered, Active, Selected, Checked)
                    if Selected then
                        engine = Checked
                        if Checked then
                            Checked = true
                            SetVehicleEngineOn(GetVehiclePedIsIn(PlayerPedId(), 0), 0, 0, 1)
                            SetVehicleUndriveable(GetVehiclePedIsIn(PlayerPedId(), 0), 1)
                            ESX.ShowNotification("Moteur éteint")
                        else
                            Checked = false
                            SetVehicleEngineOn(GetVehiclePedIsIn(PlayerPedId(), 0), 1, 0, 1)
                            SetVehicleUndriveable(GetVehiclePedIsIn(PlayerPedId(), 0), 0)
                            ESX.ShowNotification("Moteur allumé")
                        end
                    end
                end)

                RageUI.List("Fenêtre", self.fenetreList, self.fenetreIndex, nil, {}, true, function(Hovered, Active, Selected, index)

                    self.fenetreIndex = index
                    if Active then
                        if index == 1 then
                            if Selected then
                                RollDownWindows(GetVehiclePedIsIn(PlayerPedId(), true))
                            end
                        else
                            if index == 2 then
                                if Selected then
                                    for i = 0,7,1 do
                                        RollUpWindow(GetVehiclePedIsIn(PlayerPedId(), true), i)
                                        FixVehicleWindow(GetVehiclePedIsIn(PlayerPedId(), true), i)
                                    end
                                end
                            end
                        end
                    end
                end)

                RageUI.List("Capot", self.capotList, self.capotIndex, nil, {}, true, function(Hovered, Active, Selected, index)

                    self.capotIndex = index
                    if Active then
                        if index == 1 then
                            if Selected then
                                SetVehicleDoorOpen(GetVehiclePedIsIn(PlayerPedId(), true), 4, 0, 0)
                            end
                        else
                            if index == 2 then
                                if Selected then
                                    SetVehicleDoorShut(GetVehiclePedIsIn(PlayerPedId(), true), 4, 0)
                                end
                            end
                        end
                    end
                end)

                RageUI.List("Portes (Ouvrir)", self.portesList, self.portesIndex, nil, {}, true, function(Hovered, Active, Selected, index)

                    self.portesIndex = index
                    if Active then
                        if index == 1 then
                            if Selected then
                                SetVehicleDoorOpen(GetVehiclePedIsIn(PlayerPedId(), true), 0, 0, 0)
                            end
                        else
                            if index == 2 then
                                if Selected then
                                    SetVehicleDoorOpen(GetVehiclePedIsIn(PlayerPedId(), true), 1, 0, 0)
                                end
                            else
                                if index == 3 then
                                    if Selected then
                                        SetVehicleDoorOpen(GetVehiclePedIsIn(PlayerPedId(), true), 2, 0, 0)
                                    end
                                else
                                    if index == 4 then
                                        if Selected then
                                            SetVehicleDoorOpen(GetVehiclePedIsIn(PlayerPedId(), true), 3, 0, 0)
                                        end
                                    end
                                end
                            end
                        end
                    end
                end)

                RageUI.List("Portes (Fermer)", self.portesList2, self.portesIndex2, nil, {}, true, function(Hovered, Active, Selected, index)

                    self.portesIndex2 = index
                    if Active then
                        if index == 1 then
                            if Selected then
                                SetVehicleDoorShut(GetVehiclePedIsIn(PlayerPedId(), true), 0, 0)
                            end
                        else
                            if index == 2 then
                                if Selected then
                                    SetVehicleDoorShut(GetVehiclePedIsIn(PlayerPedId(), true), 1, 0)
                                end
                            else
                                if index == 3 then
                                    if Selected then
                                        SetVehicleDoorShut(GetVehiclePedIsIn(PlayerPedId(), true), 2, 0)
                                    end
                                else
                                    if index == 4 then
                                        if Selected then
                                            SetVehicleDoorShut(GetVehiclePedIsIn(PlayerPedId(), true), 3, 0)
                                        end
                                    end
                                end
                            end
                        end
                    end
                end)

                RageUI.List("Coffre", self.coffreList, self.coffreIndex, nil, {}, true, function(Hovered, Active, Selected, index)

                    self.coffreIndex = index
                    if Active then
                        if index == 1 then
                            if Selected then
                                SetVehicleDoorOpen(GetVehiclePedIsIn(PlayerPedId(), true), 5, 0, 0)
                            end
                        else
                            if index == 2 then
                                if Selected then
                                    SetVehicleDoorShut(GetVehiclePedIsIn(PlayerPedId(), true), 5, 0)
                                end
                            end
                        end
                    end
                end)

                if GetEntitySpeed(GetVehiclePedIsIn(PlayerPedId(), false))*3.6 < 1.0 then
                    RageUI.ButtonWithStyle("Sortir du véhicule moteur allumé", nil, {}, true, function(_,_,s)
                        if s then
                            Citizen.Wait(5)
                            local plyCoords = GetEntityCoords(PlayerPedId())
                            SetEntityCoords(PlayerPedId(), plyCoords.x, plyCoords.y, plyCoords.z+0.5)
                            RageUI:GoBack()
                        end
                    end)
                else
                    RageUI.ButtonWithStyle("Sortir du véhicule moteur allumé", nil, {}, false, function()
                    end)
                end

            end, function()
            end)
            if not RageUI.Visible(menuoptions) then
                menuoptions = RMenu:DeleteType("Options Véhicule", true)
            end
        end
    else
        ESX.ShowNotification("Vous n'êtes pas dans un véhicule")
    end
end