---
--- Generated by Luanalysis
--- Created by olivi.
--- DateTime: 14/02/2023 00:40
---


-- Comme Upgrade (Moteur, Suspension, Frein, Turbo, Roue, Transmission, Blindage)


function UpgradeVehicle()
    local playerPed = PlayerPedId()
    local veh = GetVehiclePedIsIn(playerPed, false)
    if IsPedInAnyVehicle(playerPed, false) then
        RageUI.CloseAll()
        local menuUP = RageUI.CreateMenu("Xenon Color", "Menu Xenon Color")
        RageUI.Visible(menuUP, not RageUI.Visible(menuUP))
        while menuUP do
            Citizen.Wait(0)
            RageUI.IsVisible(menuUP, true, true, true, function()
                RageUI.Checkbox("Moteur MAX", nil, Upgrade, {}, function(Hovered, Active, Selected, Checked)
                    Upgrade = Checked
                    if Selected then
                        Checked = true
                        SetVehicleMod(veh, 11, 3, false)
                    else
                        Checked = false
                        SetVehicleMod(veh, 11, 0, false)
                    end
                end)
                RageUI.Checkbox("Suspension MAX", nil, Suspension, {}, function(Hovered, Active, Selected, Checked)
                    Suspension = Checked
                    if Selected then
                        Checked = true
                        SetVehicleMod(veh, 15, 2, false)
                    else
                        Checked = false
                        SetVehicleMod(veh, 15, 0, false)
                    end
                end)
                RageUI.Checkbox("Frein MAX", nil, Frein, {}, function(Hovered, Active, Selected, Checked)
                    Frein = Checked
                    if Selected then
                        Checked = true
                        SetVehicleMod(veh, 12, 2, false)
                    else
                        Checked = false
                        SetVehicleMod(veh, 12, 0, false)
                    end
                end)
                RageUI.Checkbox("Turbo MAX", nil, Turbo, {}, function(Hovered, Active, Selected, Checked)
                    Turbo = Checked
                    if Selected then
                        Checked = true
                        ToggleVehicleMod(veh, 18, true)
                    else
                        Checked = false
                        ToggleVehicleMod(veh, 18, false)
                    end
                end)
                RageUI.Checkbox("Transmission MAX", nil, Transmission, {}, function(Hovered, Active, Selected, Checked)
                    Transmission = Checked
                    if Selected then
                        Checked = true
                        SetVehicleMod(veh, 13, 2, false)
                    else
                        Checked = false
                        SetVehicleMod(veh, 13, 0, false)
                    end
                end)
                RageUI.Checkbox("Blindage MAX", nil, Blindage, {}, function(Hovered, Active, Selected, Checked)
                    Blindage = Checked
                    if Selected then
                        Checked = true
                        SetVehicleMod(veh, 16, 4, false)
                    else
                        Checked = false
                        SetVehicleMod(veh, 16, 0, false)
                    end
                end)
            end)
            if not RageUI.Visible(menuUP) then
                menuUP = RMenu:DeleteType("menuUP", true)
            end
        end
    end
end